logging:
    config: classpath:logback.xml
xxl:
    job:
        accessToken: default_token
        admin:
            addresses: http://192.168.186.150:8093/xxl-job-admin
        executor:
            address: ''
            appname: ming-stock-executor
            ip: ''
            logpath: ./logs
            logretentiondays: 30
            port: 9999
